<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>vomark_redux</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="vomark-redux.Tests\**" />
    <EmbeddedResource Remove="vomark-redux.Tests\**" />
    <None Remove="vomark-redux.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ReportGenerator" Version="5.5.9" />
  </ItemGroup>

</Project>
