<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>vomark_redux</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="vomark-redux.Tests\**" />
    <EmbeddedResource Remove="vomark-redux.Tests\**" />
    <None Remove="vomark-redux.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="lib\svc\" />
  </ItemGroup>

</Project>
