# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build-Master

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ "master" ]

env:
  REPORT_DEST: coverage

jobs:
  build:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test with coverage
      run: | 
        dotnet test --no-build --verbosity normal \
        /p:CollectCoverage=True \
        /p:CoverletOutput=./$REPORT_DEST/ \
        /p:CoverletOutputFormat=cobertura

    - name: Install report generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    
    - name: Generate coverage report
      run: reportgenerator \
        -reports:$REPORT_DEST/coverage.cobertura.xml \
        -targetdir:$REPORT_DEST/reports \
        -reporttypes:textsummary

    - name: Get line coverage
      id: coverage
      run: | 
        COVERAGE=$(grep "Line coverage" coverage/report/Summary.txt | sed -E 's/.*: ([0-9.]+)%.*/\1/')
        echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

    - name: Update coverage badge
      run: |
        COVERAGE=${{ steps.coverage.outputs.coverage }}
        sed -i -E "s/coverage-[0-9]+%25/coverage-${COVERAGE}%25/" README.md

    - name: Commit badge update
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add README.md
        git commit -m "AUTOMATED - Updated coverage badge [skip ci]"
        git push



